apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
